### ISSUE TITLE
PSG enable on OSD

### ISSUE THREAD

**Issue by jotego** [phoboz/fpgagen#9]
Hi Alex,

I need a way to disable the PSG and the FM independently through the OSD and keyboard. I need this in order to debug them individually. Could you add this feature, please?

Thank you.

**Comment by phoboz** [comment]
I have added psg and fm enable/disable in the osd. PSG_ENABLE is connected to the corresponding signal on the amplifier, FM_ENABLE is connected to the LED for now.

**Comment by phoboz** [comment]
Hello Pepe,
I assign this to you now so you can connect the FM_ENABLE signal to where you want it.

**Comment by phoboz** [comment]
Done!
